### PR TITLE
Adding rounding functions

### PR DESCRIPTION
**Pull request by Krishn1412**

### CODE REVIEW

**Comment by Krishn1412** [comment]
hey @Ivorforce,
while building the project I was running into this issue
`In file included from src/ndarray.cpp:1:
In file included from src/ndarray.h:23:
src/vatensor/varray.h:14:10: fatal error: 'xtensor/xarray.hpp' file not found
#include "xtensor/xarray.hpp"           // for xarray_adaptor
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [src/ndarray.os] Error 1
scons: building terminated because of errors.`

I have written a basic structure for the rounding functions but can't test because of this failure. Can you help me out with this?
TIA

**Comment by Ivorforce** [comment]
Hi, try compiling again. It usually fails on the first try. (see #23)

**Comment by Krishn1412** [comment]
still getting the same error, I see this is a recent change

**Comment by Ivorforce** [comment]
I think the includes may fail on any (random) xtensor include. Due to #23, it does not reliably set up the 3 dependencies (xtl, xtensor, xsimd).

Try the following in your command line manually:

```
# into numdot folder
cd xtl/build && cmake ../ && cmake --install . --prefix .
# back to numbot folder
cd xsimd/build && cmake ../ -DENABLE_XTL_COMPLEX=1 -Dxtl_DIR='../xtl/build/ && cmake --install . --prefix .
# back to numdot folder
cd xtensor/build && cmake ../ -DXTENSOR_USE_XSIMD=1 -Dxtl_DIR='../xtl/build/' -Dxsimd_DIR='../xsimd/build/' && cmake --install . --prefix .
```

**Comment by Ivorforce** [comment]
Anyway, I was able to run it. Compiled fine without any tests, code looks good. I'll adjust includes and docs post-merge. Thanks!

**Comment by Ivorforce** [comment]
Reading up on the differences between rint and nearbyint, i'm deleting nearbyint and using nearbyint for the rint implementation. As i understand, rint raises when it actually had to perform rounding, which is not really useful in vectorized cases.

**Comment by 20akshay00** [comment]
@Krishn1412 I was attempting to build this on Windows 10 w/ mingw and faced the same issue. I ended up resolving it by manually building the three dependencies as mentioned above, and then removed those subcommands from the SConstruct file before running it again.

**Comment by Ivorforce** [comment]
I just removed the cmake steps from SConstruct and just added the include dirs to the project. Found no difference so far. Hopefully this eliminates these issues for good.

**Comment by Krishn1412** [comment]
yup makes sense, we won't be needing rint here

**Pull request merged**
